version: '3.9'

services:
  MySql:
    image: mysql:latest
    container_name: command-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=senha1234
      - MYSQL_DATABASE=command_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local